In [1]:
import torch


In [3]:
x = torch.empty(5,3)
print(x)

tensor([[ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.1058,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.5003,  0.0000,  0.0000]])


In [4]:
x = torch.rand(5,3)
print(x)

tensor([[ 0.3718,  0.8587,  0.9417],
        [ 0.3556,  0.6190,  0.9577],
        [ 0.5755,  0.7316,  0.5386],
        [ 0.3567,  0.3222,  0.3512],
        [ 0.7181,  0.9169,  0.1138]])


In [5]:
x = torch.zeros(5,3,dtype = torch.long)
print(x)

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])


In [6]:
x = torch.tensor([5.5,3])
print(x)

tensor([ 5.5000,  3.0000])


In [7]:
x = x.new_ones(5,3, dtype = torch.double)
print(x)

x = torch.rand_like(x, dtype = torch.float)
print(x)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)
tensor([[ 0.8510,  0.2448,  0.8078],
        [ 0.5797,  0.7771,  0.8779],
        [ 0.8562,  0.3845,  0.6433],
        [ 0.2899,  0.4039,  0.6503],
        [ 0.5368,  0.5481,  0.5254]])


In [8]:
print(x.size())

torch.Size([5, 3])


In [9]:
y = torch.rand(5,3)
print(x+y)

tensor([[ 1.3479,  0.3608,  1.2662],
        [ 1.4721,  1.3894,  1.6773],
        [ 0.9490,  0.4080,  1.2312],
        [ 0.3748,  0.8654,  1.1082],
        [ 0.8431,  1.3099,  0.6671]])


In [10]:
print(torch.add(x,y))

tensor([[ 1.3479,  0.3608,  1.2662],
        [ 1.4721,  1.3894,  1.6773],
        [ 0.9490,  0.4080,  1.2312],
        [ 0.3748,  0.8654,  1.1082],
        [ 0.8431,  1.3099,  0.6671]])


In [11]:
result = torch.empty(5,3)
torch.add(x,y, out = result)
print(result)

tensor([[ 1.3479,  0.3608,  1.2662],
        [ 1.4721,  1.3894,  1.6773],
        [ 0.9490,  0.4080,  1.2312],
        [ 0.3748,  0.8654,  1.1082],
        [ 0.8431,  1.3099,  0.6671]])


In [12]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 1.3479,  0.3608,  1.2662],
        [ 1.4721,  1.3894,  1.6773],
        [ 0.9490,  0.4080,  1.2312],
        [ 0.3748,  0.8654,  1.1082],
        [ 0.8431,  1.3099,  0.6671]])


Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.

In [13]:
print(x[:,1])

tensor([ 0.2448,  0.7771,  0.3845,  0.4039,  0.5481])


In [14]:
# Resizing: If you want to resize/reshape tensor, you can use torch.view:

x = torch.rand(4,4)
y = x.view(16)
z = x.view(-1,8)

print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [15]:
x = torch.rand(1)
print(x)
print(x.item())

tensor([ 0.3487])
0.3487452268600464


In [16]:
a = torch.ones(5)
print(a)

tensor([ 1.,  1.,  1.,  1.,  1.])


In [17]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [18]:
a.add_(1)
print(b)
print(a)

[2. 2. 2. 2. 2.]
tensor([ 2.,  2.,  2.,  2.,  2.])


In [19]:
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1, out = a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)


In [21]:
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double)) 

In [24]:
# requires_grad default value will be False
x = torch.ones(2,2,requires_grad = True)
print(x)

tensor([[ 1.,  1.],
        [ 1.,  1.]])


In [26]:
y = x + 2
print(y)

tensor([[ 3.,  3.],
        [ 3.,  3.]])


In [27]:
print(y.grad_fn)

In [35]:
z = y * y * 3
out = z.mean()

print(z, out)
#print(torch.autograd.backward(z,grad_tensors = x))

tensor([[ 27.,  27.],
        [ 27.,  27.]]) tensor(27.)


In [37]:
out.backward()

print(x.grad)

RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.

In [42]:
x = torch.randn(3, requires_grad = True)

print(x)
y = x * 2
while y.data.norm() < 1000:
    print(y.data.norm())
    print(y.data)
    y = y * 2

print(y)

tensor([ 0.3312,  0.9916,  1.5934])
tensor(3.8116)
tensor([ 0.6624,  1.9833,  3.1868])
tensor(7.6231)
tensor([ 1.3248,  3.9666,  6.3736])
tensor(15.2462)
tensor([  2.6497,   7.9332,  12.7472])
tensor(30.4925)
tensor([  5.2993,  15.8664,  25.4944])
tensor(60.9849)
tensor([ 10.5986,  31.7327,  50.9889])
tensor(121.9699)
tensor([  21.1972,   63.4655,  101.9778])
tensor(243.9398)
tensor([  42.3945,  126.9310,  203.9555])
tensor(487.8795)
tensor([  84.7890,  253.8620,  407.9110])
tensor(975.7591)
tensor([ 169.5779,  507.7239,  815.8220])
tensor([  339.1559,  1015.4478,  1631.6440])


In [43]:
gradients = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(gradients)

print(x.grad)

tensor([  102.4000,  1024.0000,     0.1024])


In [44]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


In [10]:
# perceptron (single layer network)

x = torch.tensor([[0,0,1],[1,1,1],[1,0,1],[0,1,1]], dtype = torch.float)
y = torch.tensor([[0,1,1,0]], dtype = torch.float).t()

w = torch.randn(3, 1, requires_grad = True)
learning_rate = 1e-3
for t in range(10000):
    y_pred = x.mm(w)

    loss = (y_pred - y).pow(2).sum()
    #print(loss)

    loss.backward()

    with torch.no_grad():
        w -= learning_rate * w.grad 

    w.grad.zero_()

print(torch.tensor([[1,0,1]], dtype = torch.float).mm(w))

tensor([[ 1.0000]])


In [27]:
# multi layer perceptron (2-layer feed forward networks)

x = torch.tensor([[0,0,1],[1,1,1],[1,0,1],[0,1,1]], dtype = torch.float)
y = torch.tensor([[0,0,1,1]], dtype = torch.float).t()

w1 = torch.randn(3, 4, requires_grad = True)
w2 = torch.randn(4, 1, requires_grad = True)

learning_rate = 1e-6
for t in range(500000):
    y_pred = x.mm(w1).clamp(min=0).mm(w2)
    
    loss = (y_pred - y).pow(2).sum()
    
    if t%100000 == 0:
        print(t, loss.item())
    
    loss.backward()
    
    with torch.no_grad():
        w1 -= learning_rate * w1.grad
        w2 -= learning_rate * w2.grad
    
    w1.grad.zero_()
    w2.grad.zero_()

print(torch.tensor([[1,0,1]], dtype = torch.float).mm(w1).clamp(min=0).mm(w2))

0 38.834041595458984
100000 1.243751049041748
200000 1.0478461980819702
300000 1.0097160339355469
400000 0.9988700747489929
tensor([[ 0.5040]])


In [28]:
class MyReLu(torch.autograd.Function):
    
    @staticmethod
    def forward(ctx, input):
        
        ctx.save_for_backward(input)
        return input.clamp(min=0)
    
    @staticmethod
    def backward(ctx, grad_output):
        input, = ctx.saved_tensors
        grad_input = grad_output.clone()
        grad_input[input<0] = 0
        return grad_input
    
    

In [34]:
w1 = torch.randn(3, 4, requires_grad = True)
w2 = torch.randn(4, 1, requires_grad = True)

learning_rate = 1e-6
for t in range(50000):
    relu = MyReLu.apply
    
    y_pred = relu(x.mm(w1)).mm(w2)
    
    loss = (y_pred - y).pow(2).sum()
    
    if t%10000 == 0:
        print(t, loss.item())
    
    loss.backward()
    
    with torch.no_grad():
        w1 -= learning_rate * w1.grad
        w2 -= learning_rate * w2.grad
    
    w1.grad.zero_()
    w2.grad.zero_()

print(torch.tensor([[1,0,1]], dtype = torch.float).mm(w1).clamp(min=0).mm(w2))

0 4.987572193145752
10000 3.9122745990753174
20000 3.3114094734191895
30000 2.903795003890991
40000 2.595118761062622
tensor([[ 0.5714]])


In the neural network terminology: one epoch = one forward pass and one backward pass of all the training examples. batch size = the number of training examples in one forward/backward pass. The higher the batch size, the more memory space you'll need.

In [45]:
model = torch.nn.Sequential(
    torch.nn.Linear(3, 4),
    torch.nn.ReLU(),
    torch.nn.Linear(4, 1))

loss_fn = torch.nn.MSELoss(size_average = False)

learning_rate = 1e-3
for t in range(50000):
    y_pred = model(x)
    
    loss = loss_fn(y_pred, y)
    
    if t%10000 == 0:
        print(t, loss.item())
    
    model.zero_grad()
    
    loss.backward()
    
    with torch.no_grad():
        for param in model.parameters():
            param -= learning_rate * param.grad
            
print(model(torch.tensor([[1,0,1]], dtype = torch.float)))


0 1.153525471687317
10000 2.1684607418137603e-05
20000 2.9723175032358995e-09
30000 2.0446542237095855e-09
40000 1.6718075812605093e-09
tensor([[ 1.0000]])


In [52]:
optimizer = torch.optim.Adam(model.parameters(), lr = learning_rate)

for t in range(5000):
    y_pred = model(x)
    
    loss = loss_fn(y_pred, y)
    
    if t%1000 == 0:
        print(t, loss.item())
    
    optimizer.zero_grad()
    
    loss.backward()
    
    optimizer.step()
            
print(model(torch.tensor([[1,0,1]], dtype = torch.float)))

0 0.0
1000 0.0
2000 0.0
3000 0.0
4000 0.0
tensor([[ 1.]])


In [57]:
print(model(torch.tensor([[1,1,1]], dtype = torch.float)))

tensor([[ 0.]])
