In [6]:
import torch


In [8]:
x = torch.empty(5,3)
print(x)

tensor(1.00000e-43 *
       [[ 0.0000,  0.0000,  8.4638],
        [ 0.0000,  0.0701,  0.0000],
        [    nan,  3.1389,  0.0000],
        [ 0.0000,  0.0701,  0.0000],
        [    nan,  3.1389,  0.0000]])


In [9]:
x = torch.rand(5,3)
print(x)

tensor([[ 0.7284,  0.0275,  0.0163],
        [ 0.8242,  0.3911,  0.3364],
        [ 0.2122,  0.1635,  0.5309],
        [ 0.7605,  0.6924,  0.0221],
        [ 0.6578,  0.8838,  0.9640]])


In [10]:
x = torch.zeros(5,3,dtype = torch.long)
print(x)

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])


In [11]:
x = torch.tensor([5.5,3])
print(x)

tensor([ 5.5000,  3.0000])


In [13]:
x = x.new_ones(5,3, dtype = torch.double)
print(x)

x = torch.rand_like(x, dtype = torch.float)
print(x)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)
tensor([[ 0.0068,  0.0545,  0.5763],
        [ 0.2390,  0.5831,  0.1757],
        [ 0.1942,  0.1069,  0.6628],
        [ 0.5474,  0.3933,  0.2851],
        [ 0.1510,  0.5919,  0.5036]])


In [16]:
print(x.size())

torch.Size([5, 3])


In [18]:
y = torch.rand(5,3)
print(x+y)

tensor([[ 0.4199,  0.7384,  1.1266],
        [ 0.4243,  0.6133,  0.3339],
        [ 0.4827,  0.9311,  1.6568],
        [ 0.6532,  0.5474,  0.6154],
        [ 0.5388,  1.3121,  1.3814]])


In [20]:
print(torch.add(x,y))

tensor([[ 0.4199,  0.7384,  1.1266],
        [ 0.4243,  0.6133,  0.3339],
        [ 0.4827,  0.9311,  1.6568],
        [ 0.6532,  0.5474,  0.6154],
        [ 0.5388,  1.3121,  1.3814]])


In [ ]:
result = torch.empty(5,3)
torch.